production:
  common: &common
    address: 'smtp.gmail.com'
    port: 587
    domain: 'millireview.herokuapp.com'
    authentication: 'plain'
    tls: true

  notification:
    <<: *common
    user_name: 'sachin@sproutify.com'
    password: 'kathmandu09'

  exception_notifier:
    <<: *common
    user_name: 'exception.notifier@railsbp.com'
    password: ''
